version: '3.8'
services:
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./docker/postgresql/init/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
  
volumes:
  pgdata:
    driver: local