services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./docker/postgresql/init/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql
    networks:
      - all-in-one

  api_gateway:
    container_name: api_gateway
    build:
      context: ./packages
      args:
        - SERVICE_NAME=api-gateway
    ports:
      - 3000:3000
    volumes:
      - ./packages:/app
    command: npm run start:dev api-gateway
    networks:
      - all-in-one

  user_service:
    container_name: user_service
    build:
      context: ./packages
      args:
        - SERVICE_NAME=user
        - PORT=5000
    ports:
      - 5000:5000
    depends_on:
      - postgresql
    volumes:
      - ./packages:/app
    networks:
      - all-in-one
    command: npm run start:dev user

  auth_service:
    container_name: auth_service
    build:
      context: ./packages
      args:
        - SERVICE_NAME=auth
        - PORT=5001
    ports:
      - 5001:5001
    volumes:
      - ./packages:/app
    networks:
      - all-in-one
    command: npm run start:dev auth 
  
volumes:
  pgdata:
    driver: local

networks:
  all-in-one:
    driver: bridge