// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.28.3
// source: auth.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export interface LoginRequest {
  username: string;
  password: string;
}

export interface RegisterRequest {
  username: string;
  email: string;
  password: string;
}

export interface ResponseDto {
  success: boolean;
}

export interface GenerateAccessTokenRequest {
  userId: string;
}

export interface LogoutRequest {
  userId: string;
}

export interface GenerateAccessTokenResponse {
  accessToken: string;
}

export interface Token {
  accessToken: string;
  refreshToken: string;
}

export interface AuthServiceClient {
  generateAccessToken(
    request: GenerateAccessTokenRequest,
    metadata?: Metadata,
  ): Observable<GenerateAccessTokenResponse>;

  login(request: LoginRequest, metadata?: Metadata): Observable<Token>;

  register(request: RegisterRequest, metadata?: Metadata): Observable<Token>;

  logout(request: LogoutRequest, metadata?: Metadata): Observable<ResponseDto>;
}

export interface AuthServiceController {
  generateAccessToken(
    request: GenerateAccessTokenRequest,
    metadata?: Metadata,
  ): Promise<GenerateAccessTokenResponse> | Observable<GenerateAccessTokenResponse> | GenerateAccessTokenResponse;

  login(request: LoginRequest, metadata?: Metadata): Promise<Token> | Observable<Token> | Token;

  register(request: RegisterRequest, metadata?: Metadata): Promise<Token> | Observable<Token> | Token;

  logout(request: LogoutRequest, metadata?: Metadata): Promise<ResponseDto> | Observable<ResponseDto> | ResponseDto;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["generateAccessToken", "login", "register", "logout"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
