import type { Metadata } from 'next/types'

import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme='auto' />
      </head>
      <body>
        <MantineProvider defaultColorScheme='auto'>{children}</MantineProvider>
      </body>
    </html>
  )
}
