-- Active: 1732022150969@@127.0.0.1@5432@postgres
CREATE ROLE "aio_user" with PASSWORD "aio_user" LOGIN;

CREATE SCHEMA IF NOT EXISTS "user";

GRANT USAGE ON SCHEMA "user" TO "aio_user";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "user" TO "aio_user";

ALTER DEFAULT PRIVILEGES IN SCHEMA "user"

GRANT ALL PRIVILEGES ON TABLES TO "aio_user";

CREATE ROLE "aio_auth" with PASSWORD 'aio_auth' LOGIN;

CREATE SCHEMA IF NOT EXISTS "auth";

GRANT USAGE ON SCHEMA "auth" TO "aio_auth";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "auth" TO "aio_auth";

ALTER DEFAULT PRIVILEGES IN SCHEMA "auth"
GRANT ALL PRIVILEGES ON TABLES TO "aio_auth";